<a href="https://colab.research.google.com/github/berkanttubi/NumpyCheatSheet/blob/main/NumpyCheatSheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CREATING ARRAY

While creating numpy array, if the type does nt match, Numpy will upcast it if possible. If we want to explicitly set the data type of the resulting array, we can use the dtype *keyword*:




In [ ]:
import numpy as np

#Create integer array
np.array([1,2,4,5])

#Type upcasting
np.array([3.14,1,2,5])

#dtype keyword
np.array([1,2,3,4],dtype='float32')

#multidimensional array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# CREATING ARRAY FROM SCRATCH



In [ ]:
#lengtht 10 , integer zeros
np.zeros(10,dtype='int')

#Create 3x5 integer ones
np.ones((3,5),dtype='int')

#Create array fullfilled with any specific value
np.full((3,5),3.14)

#Like built-in range function
np.arange(0,10,2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

#Random between 0-1
np.random.random((3,5))

#Random wiht mean=0, std=1
np.random.normal(0,1,(3,3))

#Random integers in a range
np.random.randint(0,20,(3,3))

array([[15, 18, 16],
       [ 4,  3, 17],
       [13, 18, 18]])

# NUMPY ARRAY ATTRIBUTES

In [ ]:
x1= np.random.randint(10,size=6) #One dimensional
x2= np.random.randint(10, size=(3,4)) #Two dimensional
x3= np.random.randint(10, size = (3,4,5)) #Three dimensional

print(x3)
print("\n x3 ndim: ", x3.ndim) #Number of dimension
print("x3 shape:", x3.shape) #Size of each dimension
print("x3 size: ", x3.size) #size
print("x3 dtype: ", x3.dtype) #Dtype

[[[8 4 9 9 9]
  [8 3 4 9 4]
  [4 0 3 5 3]
  [4 9 6 9 6]]

 [[0 0 3 6 6]
  [5 2 1 1 6]
  [8 1 0 7 4]
  [4 5 1 2 1]]

 [[9 7 1 9 9]
  [8 7 4 3 9]
  [0 8 5 5 5]
  [0 4 7 8 4]]]

 x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x3 dtype:  int64


!!! One important—and extremely useful—thing to know about array slices is that they
return views rather than copies of the array data. This is one area in which NumPy
array slicing differs from Python list slicing: in lists, slices will be copies.


In [ ]:
print(x2)
x2_sub = x2[:2,:2]
print(x2_sub)

[[0 8 2 8]
 [0 0 6 7]
 [9 4 9 7]]
[[0 8]
 [0 0]]


In [ ]:
x2_sub[0,0] = 99
print(x2)

[[99  8  2  8]
 [ 0  0  6  7]
 [ 9  4  9  7]]


To create and copy of an array we use copy() method


In [ ]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  8]
 [ 0  0]]


In [ ]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)
print(x2[:2,:2])

[[42  8]
 [ 0  0]]
[[99  8]
 [ 0  0]]


# RESHAPING ARRAYS
Note that for this to work, the size of the initial array must match the size of the
reshaped array. Where possible, the reshape method will use a no-copy view of the
initial array




In [ ]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


One dimensional array to two dimensional array; 

In [ ]:
#One method to do that is reshape()
x= np.array([1,2,3])
x.reshape(3,1)

#Another method is newaxıs
x= np.array([1,2,3])
x[:,np.newaxis]


array([[1],
       [2],
       [3]])

# ARRAY CONCATENATION AND SPLITTING

###Concatenation of arrays 

In [ ]:
x= np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
#You can also concatenate more than two arrays at once:
z = np.array([9,9,9])
np.concatenate([x,y,z])

array([1, 2, 3, 3, 2, 1, 9, 9, 9])

In [ ]:
#You can also concatenate 2-D arrays at once:
grid = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([grid,grid])

#Concatenate along the second axixs(zero-indexed)
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Working arrays with mixed dimensions

In [ ]:
#vertical stack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
np.vstack([grid,x])

#horizontal stack
y = np.array([[99],
              [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

###Splitting

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3, x4 = np.split(x, [2,5,7])
print(x1, x2, x3, x4)

[1 2] [ 3 99 99] [3 2] [1]


In [ ]:
#Vertical split
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#Horizontal split
grid = np.arange(16).reshape((4, 4))
print(grid)
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# UNIVERSAL FUNCTIONS

#### Specifying Output

In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


#### Aggregates

In [ ]:
# Reduce()
x=np.arange(6)
np.add.reduce(x)

15

In [ ]:
#Accummulate
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10, 15])

#### Comparison Operators

In [ ]:
x=np.array([1,2,3,4,5])
print(x<3)
print(x>3)
print(x!=3)
print(x==3)

[ True  True False False False]
[False False False  True  True]
[ True  True False  True  True]
[False False  True False False]


In [ ]:
#Counting
print(np.count_nonzero(x<6))
print(np.sum(x<6))

5
5


In [ ]:
#How many values less than 6 in each row?
x = np.array([[5,0,3,3],
              [7,9,3,5],
              [2,4,7,6]])
np.sum(x<6, axis=1)

array([4, 2, 2])

In [ ]:
#Any values greater than 6?
np.any(x>6)

#Any values less than 0?
np.any(x<0)

#All values less than 10?
np.all(x<10)

True

#### Selection

In [ ]:
x = np.array([[5,0,3,3],
              [7,9,3,5],
              [2,4,7,6]])
x[x<5]

array([0, 3, 3, 3, 2, 4])

#### Sorting

In [ ]:
#Sort() function returns the sorted list
x= np.array([3,2,1,10,7,11,8,0])
np.sort(x)

array([ 0,  1,  2,  3,  7,  8, 10, 11])

In [ ]:
#Argsort() returns the indexes of the array
i=np.argsort(x)
print(i)

[7 2 1 0 4 6 3 5]


In [ ]:
x[i]

array([ 0,  1,  2,  3,  7,  8, 10, 11])

In [ ]:
#K smallest value in array
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3) #Elements will have arbitrary order

array([2, 1, 3, 4, 6, 5, 7])